import { db, visaResourceSourcesTable } from "@workspace/db";
import type { InsertVisaResourceSource } from "@workspace/db";
import type { VisaResourceSource } from "@workspace/db";

export const visaResourceCatalog: InsertVisaResourceSource[] = [
  {
    id: "czechia-employee-card",
    destinationCountry: "Czechia",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Employee Card",
    title: "Employee Card",
    description: "Official entry point for Czechia's Employee Card. Check the current route, application steps, and supporting evidence with the authority.",
    sourceName: "Czech Ministry of the Interior · Employee Card",
    sourceUrl: "https://ipc.gov.cz/en/visa-and-residence-permit-types/third-country-nationals/long-term-residence-permits/employee-card/",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "germany-eu-blue-card",
    destinationCountry: "Germany",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "EU Blue Card",
    title: "EU Blue Card",
    description: "Official information for Germany's EU Blue Card route. Confirm current qualifications, salary, and application requirements on the source page.",
    sourceName: "Make it in Germany · official portal",
    sourceUrl: "https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "canada-express-entry",
    destinationCountry: "Canada",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Express Entry",
    title: "Express Entry",
    description: "Official Government of Canada information about Express Entry immigration programs and application steps.",
    sourceName: "Government of Canada · Express Entry",
    sourceUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "uk-skilled-worker",
    destinationCountry: "United Kingdom",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Skilled Worker visa",
    title: "Skilled Worker visa",
    description: "Official GOV.UK information about the Skilled Worker route. Check the current sponsor, job, salary, and application requirements.",
    sourceName: "GOV.UK · Skilled Worker visa",
    sourceUrl: "https://www.gov.uk/skilled-worker-visa",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "ireland-critical-skills",
    destinationCountry: "Ireland",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Critical Skills Employment Permit",
    title: "Critical Skills Employment Permit",
    description: "Official information about Ireland's Critical Skills Employment Permit and its current occupation and employment conditions.",
    sourceName: "Ireland Department of Enterprise · Critical Skills",
    sourceUrl: "https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/critical-skills-employment-permit/",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "netherlands-highly-skilled-migrant",
    destinationCountry: "Netherlands",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Highly skilled migrant residence permit",
    title: "Highly skilled migrant residence permit",
    description: "Official Dutch Immigration and Naturalisation Service information for the highly skilled migrant residence permit.",
    sourceName: "Dutch Immigration and Naturalisation Service",
    sourceUrl: "https://ind.nl/en/residence-permits/work/highly-skilled-migrant",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "new-zealand-aewv",
    destinationCountry: "New Zealand",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Accredited Employer Work Visa",
    title: "Accredited Employer Work Visa",
    description: "Official Immigration New Zealand information about the Accredited Employer Work Visa and its current requirements.",
    sourceName: "Immigration New Zealand · AEWV",
    sourceUrl: "https://www.immigration.govt.nz/new-zealand-visas/visas/visa/accredited-employer-work-visa",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "singapore-employment-pass",
    destinationCountry: "Singapore",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Employment Pass",
    title: "Employment Pass",
    description: "Official Singapore Ministry of Manpower information about the Employment Pass and current application conditions.",
    sourceName: "Singapore Ministry of Manpower",
    sourceUrl: "https://www.mom.gov.sg/passes-and-permits/employment-pass",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "portugal-digital-nomad",
    destinationCountry: "Portugal",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Remote work residence route",
    title: "Remote work residence route",
    description: "Official Portuguese government information about residence for remote professional activity.",
    sourceName: "ePortugal · government services",
    sourceUrl: "https://eportugal.gov.pt/en/servicos/obter-um-visto-de-residencia-para-o-exercicio-de-atividade-profissional-prestada-de-forma-remota",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "austria-red-white-red-card",
    destinationCountry: "Austria",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Red-White-Red Card",
    title: "Red-White-Red Card",
    description: "Official Austrian government information about immigration and residence pathways, including the Red-White-Red Card.",
    sourceName: "Migration.gv.at · Red-White-Red Card",
    sourceUrl: "https://www.migration.gv.at/en/types-of-immigration/permanent-immigration/",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "belgium-single-permit",
    destinationCountry: "Belgium",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Single Permit",
    title: "Single Permit",
    description: "Official Belgian information about the Single Permit process and current regional requirements.",
    sourceName: "Working in Belgium · Single Permit",
    sourceUrl: "https://onestopcounter.workinginbelgium.be/en/fixed-term-single-permit.html",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "finland-specialist",
    destinationCountry: "Finland",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Residence permit for a specialist",
    title: "Residence permit for a specialist",
    description: "Official Finnish Immigration Service information about the specialist residence permit.",
    sourceName: "Finnish Immigration Service · Specialist",
    sourceUrl: "https://migri.fi/en/specialist",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "france-talent-passport",
    destinationCountry: "France",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Talent Passport",
    title: "Talent Passport",
    description: "Official France-Visas information about the Talent Passport categories and application route.",
    sourceName: "France-Visas · Talent Passport",
    sourceUrl: "https://france-visas.gouv.fr/en/web/france-visas/talents-internationaux-et-attractivite-economique",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "japan-engineer-specialist",
    destinationCountry: "Japan",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Engineer / Specialist in Humanities / International Services",
    title: "Engineer / Specialist in Humanities / International Services",
    description: "Official Immigration Services Agency of Japan information about professional work statuses of residence.",
    sourceName: "Immigration Services Agency of Japan · Work statuses",
    sourceUrl: "https://www.moj.go.jp/isa/applications/status/gijinkoku.html?hl=en&lang=en",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "norway-skilled-worker",
    destinationCountry: "Norway",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Skilled worker residence permit",
    title: "Skilled worker residence permit",
    description: "Official Norwegian Directorate of Immigration information about skilled worker residence permits.",
    sourceName: "UDI · Skilled workers",
    sourceUrl: "https://www.udi.no/en/want-to-apply/work-immigration/skilled-workers?c=nor",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "spain-international-teleworker",
    destinationCountry: "Spain",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "International teleworker residence",
    title: "International teleworker residence",
    description: "Official Spanish government information about residence for international teleworkers.",
    sourceName: "Spanish Ministry of Inclusion · International teleworkers",
    sourceUrl: "https://www.inclusion.gob.es/en/web/unidadgrandesempresas/teletrabajadores",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "sweden-work-permit",
    destinationCountry: "Sweden",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Work permit",
    title: "Work permit",
    description: "Official Swedish Migration Agency information about work permits for employees.",
    sourceName: "Swedish Migration Agency · Work permit",
    sourceUrl: "https://www.migrationsverket.se/en/you-want-to-apply/work/employee-or-self-employed/employees.html",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "australia-skilled-independent-189",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Skilled Independent visa (subclass 189)",
    title: "Skilled Independent visa (subclass 189)",
    description: "Official Department of Home Affairs information for the Skilled Independent visa and its current application requirements.",
    sourceName: "Australian Department of Home Affairs",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "australia-skilled-nominated-190",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Skilled Nominated visa (subclass 190)",
    title: "Skilled Nominated visa (subclass 190)",
    description: "Official Department of Home Affairs information for the Skilled Nominated visa and its current application requirements.",
    sourceName: "Australian Department of Home Affairs",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "australia-skills-in-demand-482",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "Skills in Demand visa (subclass 482)",
    title: "Skills in Demand visa (subclass 482)",
    description: "Official Department of Home Affairs information for the Skills in Demand visa and its current application requirements.",
    sourceName: "Australian Department of Home Affairs",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skills-in-demand-482",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "australia-national-innovation-858",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["work"],
    recordKind: "pathway",
    pathwayName: "National Innovation visa (subclass 858)",
    title: "National Innovation visa (subclass 858)",
    description: "Official Department of Home Affairs information for the National Innovation visa and its current application requirements.",
    sourceName: "Australian Department of Home Affairs",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/national-innovation-858",
    reviewedOn: "2026-09-18",
    authority: "official",
  },
  {
    id: "australia-student-500",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["study"],
    recordKind: "pathway",
    pathwayName: "Student visa (subclass 500)",
    title: "Student visa (subclass 500)",
    description: "Official information for people planning to study in Australia, including the current eligibility and application steps.",
    sourceName: "Australian Department of Home Affairs",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "australia-training-407",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["training"],
    recordKind: "pathway",
    pathwayName: "Training visa (subclass 407)",
    title: "Training visa (subclass 407)",
    description: "Official information about workplace-based occupational training in Australia for skills development and professional training.",
    sourceName: "Australian Department of Home Affairs",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/training-407",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "australia-visitor-tourist-onshore",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["visit"],
    recordKind: "stream",
    pathwayName: "Visitor visa (subclass 600)",
    title: "Tourist stream · apply in Australia",
    description: "Official page for this Visitor visa stream. Open Home Affairs for current conditions, eligibility, and application details.",
    sourceName: "Australian Department of Home Affairs",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600/tourist-stream-onshore",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "australia-visitor-tourist-offshore",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["visit"],
    recordKind: "stream",
    pathwayName: "Visitor visa (subclass 600)",
    title: "Tourist stream · apply outside Australia",
    description: "Official page for this Visitor visa stream. Open Home Affairs for current conditions, eligibility, and application details.",
    sourceName: "Australian Department of Home Affairs",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600/tourist-stream-overseas",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "australia-visitor-sponsored-family",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["visit"],
    recordKind: "stream",
    pathwayName: "Visitor visa (subclass 600)",
    title: "Sponsored family stream",
    description: "Official page for this sponsored Visitor visa stream. Open Home Affairs for current sponsorship conditions, eligibility, and application details.",
    sourceName: "Australian Department of Home Affairs",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600/sponsored-family-stream",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "australia-visitor-visa-finder",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business", "training"],
    recordKind: "finder",
    pathwayName: "Australian Visa Finder",
    title: "Official Australian Visa Finder",
    description: "Answer Home Affairs questions about your passport, intended activity, stay, and application method to see current visa options. Results can be broader than Pathfinder's maintained route examples.",
    sourceName: "Australian Department of Home Affairs · Visa Finder",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-finder",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-australia",
    destinationCountry: "Australia",
    passportCountries: [],
    purposeTags: ["work", "visit", "business"],
    recordKind: "finder",
    pathwayName: "Australian visa list",
    title: "Australian visa list",
    description: "Official Home Affairs directory grouped by visa purpose. It includes a separate repealed-visas section, so open an individual current visa page to confirm availability and conditions.",
    sourceName: "Australian Department of Home Affairs · Visa list",
    sourceUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-austria",
    destinationCountry: "Austria",
    passportCountries: [],
    purposeTags: ["work", "study", "business"],
    recordKind: "finder",
    pathwayName: "Austria immigration options",
    title: "Explore work, study and residence options",
    description: "The Austrian Government migration portal links to work, study, family and business routes. Short-stay visa categories are covered separately by the official visa-types guide.",
    sourceName: "Austrian Government · Migration.gv.at",
    sourceUrl: "https://www.migration.gv.at/en/living-and-working-in-austria",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-visit-austria",
    destinationCountry: "Austria",
    passportCountries: [],
    purposeTags: ["visit", "business"],
    recordKind: "finder",
    pathwayName: "Austria visa types",
    title: "Austria visa types",
    description: "Official overview of Austria's A, C and D visa categories. Check passport-specific requirements and the relevant individual visa page; this overview is not an eligibility decision.",
    sourceName: "oesterreich.gv.at · Visa types",
    sourceUrl: "https://www.oesterreich.gv.at/en/themen/menschen_aus_anderen_staaten/visum_fuer_oesterreich/Seite.3550020",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-belgium",
    destinationCountry: "Belgium",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "Belgium immigration and visa information",
    title: "Travel to or settle in Belgium",
    description: "The Belgian Immigration Office's third-country national overview explains short-stay and long-stay visas and links to residence topics. Follow the purpose-specific pages for current requirements.",
    sourceName: "Belgian Immigration Office · FPS Home Affairs",
    sourceUrl: "https://dofi.ibz.be/en/themes/third-country-nationals",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-canada",
    destinationCountry: "Canada",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "Canada immigration and citizenship",
    title: "Explore Canadian immigration programs",
    description: "Government of Canada index for visiting, working, studying and immigrating, with a guided tool for exploring programs. Use the linked program page for current details.",
    sourceName: "Government of Canada · Immigration and citizenship",
    sourceUrl: "https://www.canada.ca/en/services/immigration-citizenship.html",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-czechia",
    destinationCountry: "Czechia",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "Czech visa and residence permit types",
    title: "Visa and residence permit types",
    description: "The Czech Ministry of the Interior's official portal groups visa and residence information by applicant category. Open the relevant category for purpose-specific requirements.",
    sourceName: "Czech Ministry of the Interior · Information Portal for Foreigners",
    sourceUrl: "https://ipc.gov.cz/en/visa-and-residence-permit-types",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-finland",
    destinationCountry: "Finland",
    passportCountries: [],
    purposeTags: ["work", "study", "business"],
    recordKind: "finder",
    pathwayName: "Finnish residence permit types",
    title: "Residence permit types",
    description: "The Finnish Immigration Service's official index covers residence permits, including work, study and family grounds. Short visits are handled separately by Finland's Ministry for Foreign Affairs.",
    sourceName: "Finnish Immigration Service · Residence permit types",
    sourceUrl: "https://migri.fi/en/residence-permit-types",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-visit-finland",
    destinationCountry: "Finland",
    passportCountries: [],
    purposeTags: ["visit", "business"],
    recordKind: "finder",
    pathwayName: "Visa to visit Finland",
    title: "Short-stay visa for Finland",
    description: "Official Ministry for Foreign Affairs guidance for short, temporary visits, including how to check whether a visa is needed. Longer stays use residence permits.",
    sourceName: "Finland Ministry for Foreign Affairs · Visa to visit Finland",
    sourceUrl: "https://um.fi/visa-to-visit-finland",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-france",
    destinationCountry: "France",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "France-Visas",
    title: "Find the right visa for France",
    description: "France's official visa portal lets applicants check their situation and follow the visa application process. Use its result and linked visa pages for current requirements.",
    sourceName: "France-Visas · Official visa portal",
    sourceUrl: "https://france-visas.gouv.fr/en/web/france-visas",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-germany",
    destinationCountry: "Germany",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "German visa service",
    title: "Visa types and application information",
    description: "The Federal Foreign Office's visa-service index explains visa types, where to apply and related steps. For route-specific work and study guidance, follow the linked official pages.",
    sourceName: "German Federal Foreign Office · Visa & Service",
    sourceUrl: "https://www.auswaertiges-amt.de/en/visa-service/215870-215870",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-ireland",
    destinationCountry: "Ireland",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "Coming to Ireland",
    title: "Explore options for coming to Ireland",
    description: "Ireland's Immigration Service Delivery hub links visitors to official Visit, Work, Study, Live and Join Family sections. Follow the relevant section for current rules.",
    sourceName: "Irish Immigration Service · Immigration Service Delivery",
    sourceUrl: "https://www.irishimmigration.ie/",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-japan",
    destinationCountry: "Japan",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "Japan visa information",
    title: "Visa information for Japan",
    description: "Japan's Ministry of Foreign Affairs groups visitor and long-term visa information. It directs applicants to the Japanese diplomatic mission responsible for their place of residence for detailed instructions.",
    sourceName: "Japan Ministry of Foreign Affairs · Visa",
    sourceUrl: "https://www.mofa.go.jp/j_info/visit/visa/index.html",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-netherlands",
    destinationCountry: "Netherlands",
    passportCountries: [],
    purposeTags: ["work", "study", "business"],
    recordKind: "finder",
    pathwayName: "Dutch residence permits",
    title: "Explore residence permits",
    description: "The Dutch Immigration and Naturalisation Service's official index links to residence permit categories, including work and study. Short stays have a separate IND section.",
    sourceName: "Dutch Immigration and Naturalisation Service · Residence permits",
    sourceUrl: "https://ind.nl/en/residence-permits",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-visit-netherlands",
    destinationCountry: "Netherlands",
    passportCountries: [],
    purposeTags: ["visit", "business"],
    recordKind: "finder",
    pathwayName: "Netherlands short stay",
    title: "Short-stay visa and visit information",
    description: "Official IND information for visits of up to 90 days, including holiday, family and business visits. It links to the steps and nationality requirements that apply.",
    sourceName: "Dutch Immigration and Naturalisation Service · Short stay",
    sourceUrl: "https://ind.nl/en/short-stay",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-new-zealand",
    destinationCountry: "New Zealand",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "New Zealand visa search",
    title: "Find and compare New Zealand visas",
    description: "Immigration New Zealand's official visa search lists visa options and provides filters for exploring categories. Open the relevant visa page to confirm current eligibility and conditions.",
    sourceName: "Immigration New Zealand · Visa search",
    sourceUrl: "https://www.immigration.govt.nz/new-zealand-visas",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-norway",
    destinationCountry: "Norway",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "Norway application guide",
    title: "Explore applications for Norway",
    description: "UDI's official application guide tailors information and forms to the applicant's answers, including citizenship and purpose. Some pages require those choices before showing details.",
    sourceName: "Norwegian Directorate of Immigration · UDI",
    sourceUrl: "https://www.udi.no/en/want-to-apply",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-portugal",
    destinationCountry: "Portugal",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "Portugal visa portal",
    title: "Explore visas for Portugal",
    description: "Portugal's Ministry of Foreign Affairs visa portal links to short-stay and national visa categories. Residence-permit steps after arrival may be handled by AIMA.",
    sourceName: "Portugal Ministry of Foreign Affairs · Visa portal",
    sourceUrl: "https://vistos.mne.gov.pt/en/",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-singapore",
    destinationCountry: "Singapore",
    passportCountries: [],
    purposeTags: ["study"],
    recordKind: "finder",
    pathwayName: "Singapore residence and study information",
    title: "Explore residence and study options",
    description: "ICA's official hub links to residence and Student's Pass categories. Work passes are administered separately by the Ministry of Manpower, and short-stay entry visas use a separate ICA check.",
    sourceName: "Singapore Immigration & Checkpoints Authority · Reside",
    sourceUrl: "https://www.ica.gov.sg/reside",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-visit-singapore",
    destinationCountry: "Singapore",
    passportCountries: [],
    purposeTags: ["visit", "business"],
    recordKind: "finder",
    pathwayName: "Singapore entry visa check",
    title: "Check Singapore entry-visa requirements",
    description: "ICA's official check explains whether a travel document requires an entry visa. A visa does not guarantee entry; work and study permissions are separate.",
    sourceName: "Singapore Immigration & Checkpoints Authority · Entry visa",
    sourceUrl: "https://www.ica.gov.sg/enter-transit-depart/entering-singapore/visa_requirements",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-work-singapore",
    destinationCountry: "Singapore",
    passportCountries: [],
    purposeTags: ["work", "business"],
    recordKind: "finder",
    pathwayName: "Singapore work passes and permits",
    title: "Explore work passes and permits",
    description: "The Ministry of Manpower's official index covers Singapore work passes and permits. Work-pass requirements depend on the role, employer and applicant circumstances.",
    sourceName: "Singapore Ministry of Manpower · Passes and permits",
    sourceUrl: "https://www.mom.gov.sg/passes-and-permits",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-spain",
    destinationCountry: "Spain",
    passportCountries: [],
    purposeTags: ["work", "study", "business"],
    recordKind: "finder",
    pathwayName: "Spain residence authorization types",
    title: "Explore residence and work authorizations",
    description: "Spain's Ministry of Inclusion provides a category index and complete list of immigration authorizations for living and working in Spain. This is not a short-stay visitor-visa list.",
    sourceName: "Spanish Ministry of Inclusion · Migrations",
    sourceUrl: "https://www.inclusion.gob.es/en/web/migraciones/tipos-de-autorizacion",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-visit-spain",
    destinationCountry: "Spain",
    passportCountries: [],
    purposeTags: ["visit", "business"],
    recordKind: "finder",
    pathwayName: "Schengen short-stay visa policy",
    title: "Short-stay Schengen visa information",
    description: "The European Commission's official short-stay visa policy applies to Spain. For Spanish consulate, appointment and application details, use the mission responsible for where you apply.",
    sourceName: "European Commission · Schengen visa policy",
    sourceUrl: "https://home-affairs.ec.europa.eu/policies/schengen/visa-policy_en",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-sweden",
    destinationCountry: "Sweden",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "Swedish Migration Agency application guide",
    title: "Explore applications for Sweden",
    description: "The Swedish Migration Agency's official application hub links to work, study, visitor and residence categories. Follow the relevant category for current requirements.",
    sourceName: "Swedish Migration Agency · You want to apply",
    sourceUrl: "https://www.migrationsverket.se/en/you-want-to-apply.html",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
  {
    id: "destination-visa-directory-united-kingdom",
    destinationCountry: "United Kingdom",
    passportCountries: [],
    purposeTags: ["work", "study", "visit", "business"],
    recordKind: "finder",
    pathwayName: "UK visas and immigration",
    title: "Explore UK visas and immigration",
    description: "GOV.UK's official index links to visitor, work, study, settlement and other immigration topics, including tools to check which permission may be needed.",
    sourceName: "GOV.UK · Visas and immigration",
    sourceUrl: "https://www.gov.uk/visas-immigration",
    reviewedOn: "2026-10-06",
    authority: "official",
  },
];

type VisaSourceApplicability = {
  purposeTags: string[];
  passportCountries?: string[] | null;
};

export function filterApplicableVisaSources<T extends VisaSourceApplicability>(
  sources: T[],
  purposeTag: string,
  passportCountry?: string,
): T[] {
  const normalizedPassport = passportCountry?.trim().toLowerCase();
  return sources
    .filter((source) => source.purposeTags.includes(purposeTag))
    .filter((source) => (source.passportCountries ?? []).length === 0
      || Boolean(normalizedPassport && source.passportCountries?.some(
        (country) => country.toLowerCase() === normalizedPassport,
      )));
}

export async function ensureVisaResourceCatalog(): Promise<void> {
  for (const source of visaResourceCatalog) {
    await db
      .insert(visaResourceSourcesTable)
      .values(source)
      .onConflictDoUpdate({
        target: visaResourceSourcesTable.id,
        // Sync curated catalogue copy while preserving access/monitoring state and staged URL changes.
        set: {
          destinationCountry: source.destinationCountry,
          passportCountries: source.passportCountries,
          purposeTags: source.purposeTags,
          recordKind: source.recordKind,
          pathwayName: source.pathwayName,
          title: source.title,
          description: source.description,
          sourceName: source.sourceName,
          reviewedOn: source.reviewedOn,
          authority: source.authority,
        },
      });
  }
}
